# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        go-version: ['1.20', '1.21']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -v

    - name: List Docker Images
      run: docker images
    
    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2